import type { Metadata } from "next";
import RootLayout from "@/components/RootLayout";

export const metadata: Metadata = {
  title: "Texas Wellnas",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/loader-img.png",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}
