
import Link from 'next/link';
import type { Metadata } from "next";
import bar2 from '../../assets/images/bars2.png';
import ReadyToGetStarted from '@/components/ui/ReadyToGetStarted';
import AntiAgingFAQ from '@/components/ui/AntiAgingFAQ';
import Image from 'next/image';


export const metadata: Metadata = {
    title: "Texas Wellnas | Anti-Aging",
    description: "Generated by create next app",
   
  };

const AntiAging = () => {
    return (
        <>
            <section className="all-services-section">
                <div className="container">
                    <div className="row">
                        <div className="col-md-12">
                            <div className="all-service-wrap">
                                <Image src={bar2} alt="image" style={{ width: "100px" }} />
                                <h6>Anti <span> Aging </span> </h6>
                                <p>Experience a new approach to anti-aging at Texas Center Wellness. Your journey to ageless living starts here.</p>
                                <div className="row">
                                    <div className="col-md-5"></div>
                                    <div className="col-md-2">
                                        <Link href="https://payment.texascenterwellness.com/">
                                            <button>SIGN UP TODAY</button>
                                        </Link>
                                    </div>
                                    <div className="col-md-5"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="care-wrap">
                <div className="container" data-aos="fade-up" data-aos-duration="1000">
                    <div className="row">
                        <div className="col-md-12">
                            <div className="card sec-toper global-service">
                                <div className="card-body">
                                    <div data-aos="fade-up" data-aos-duration="1000">
                                        <h6>The Texas Center Wellness Anti-Aging Approach</h6>
                                        <p>
                                            We embrace a holistic and personalized approach to help you age gracefully and live your best life. Our integrative method to anti-aging focuses on enhancing your overall well-being while addressing the underlying factors that contribute to the aging process. We create a customized anti-aging plan that considers your goals, medical history, and lifestyle. No two individuals are the same, and your plan will be tailored to your needs.
                                        </p>
                                    </div>
                                    <br />
                                    <div data-aos="fade-up" data-aos-duration="1000">
                                        <h6>Understanding Anti-Aging</h6>
                                        <p>
                                            Anti-aging encompasses a range of practices and therapies aimed at slowing down or reversing the effects of aging, enhancing longevity, and improving the quality of life. This field combines lifestyle changes, nutritional guidance, and advanced treatments to address aging at the cellular level, promoting healthier skin, improved physical health, and overall well-being. By focusing on prevention and the maintenance of optimal health, anti-aging strategies strive to extend the youthful aspects of life and delay the onset of age-related conditions.
                                        </p>
                                    </div>
                                    <br />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="care-wrap">
                <div className="container" data-aos="fade-up" data-aos-duration="1000">
                    <div className="row benefits-wrap pt-5">
                        <div className="col-md-4 mb-4">
                            <div className="card">
                                <div className="card-body">
                                    <div>
                                        <h6>Lifestyle Assessment</h6>
                                        <p>Our expert practitioners perform a comprehensive evaluation to understand your unique health profile, including physical, mental, and emotional aspects.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-4 mb-4">
                            <div className="card">
                                <div className="card-body">
                                    <div>
                                        <h6>Personalized Plan </h6>
                                        <p>Our focus extends beyond short-term results. We empower you with tools for sustained well-being and graceful aging throughout your life.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className="col-md-4 mb-4">
                            <div className="card">
                                <div className="card-body">
                                    <div>
                                        <h6>Functional Medicine</h6>
                                        <p>Functional Medicine discovers and addresses its underlying causes.Unlike conventional medicine, Functional Medicine addresses the patient as a whole - not as an isolated set of systems and symptoms.</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <section className="care-wrap">
                <AntiAgingFAQ />
            </section>

            <section className="care-wrap pt-5">
                <ReadyToGetStarted extraText="Embark on your personalized anti-aging journey. Let us guide you toward a future of timeless well-being." btnText="START TODAY" />
            </section>

        </>

    );
};

export default AntiAging;
